#!/usr/bin/env python3
"""Locally transcribe Adelaide YouTube uploads without usable captions."""

from __future__ import annotations

import argparse
import json
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path

from archive_adelaide_youtube import MANIFEST, SOURCE_ROOT, YOUTUBE_SOURCES, note_map
from transcribe_marriage_podcasts import MODEL, clean_text, normalize_segments, safe_filename, timestamp, transcript_blocks


ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "Marriage Wiki"
ASR_DIR = WIKI / "raw" / "asr" / "Adelaide Heward-Mills YouTube"
STATE = WIKI / "_meta" / "adelaide-youtube-whisper-state.json"
TMP = ROOT / "pipeline" / "tmp" / "adelaide-youtube"
YTDLP = "/opt/homebrew/bin/yt-dlp"


def write_state(state):
    STATE.parent.mkdir(parents=True, exist_ok=True)
    state["updated"] = datetime.now(timezone.utc).isoformat()
    STATE.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def download_audio(entry):
    TMP.mkdir(parents=True, exist_ok=True)
    template = TMP / f"{entry['video_id']}.%(ext)s"
    subprocess.run([
        YTDLP, "--no-playlist", "--no-warnings", "--no-progress",
        "-f", "bestaudio/worst", "--extract-audio", "--audio-format", "m4a", "--audio-quality", "9",
        "--postprocessor-args", "ffmpeg:-ac 1 -ar 16000", "-o", str(template), entry["url"],
    ], check=True, timeout=1800)
    candidates = sorted(TMP.glob(f"{entry['video_id']}.*"))
    if not candidates:
        raise RuntimeError("yt-dlp produced no audio file")
    return candidates[0]


def save_asr(entry, result, segments):
    ASR_DIR.mkdir(parents=True, exist_ok=True)
    path = ASR_DIR / f"{entry['video_id']}.json"
    payload = {
        "source_id": entry["source_id"], "model": MODEL,
        "language": result.get("language", "en"),
        "text": clean_text(result.get("text", "")), "segments": segments,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return path


def write_note(entry, asr_path, segments):
    metadata = {
        "title": entry["title"], "source_id": entry["source_id"],
        "speaker": ["Adelaide Heward-Mills"], "speaker_attribution": "channel_creator_unverified",
        "series": "Adelaide Heward-Mills", "collection": "Adelaide Heward-Mills — YouTube",
        "platform": "YouTube", "source_url": entry["url"], "video_url": entry["url"],
        "video_id": entry["video_id"], "published": entry.get("published"),
        "duration_seconds": entry.get("duration_seconds"),
        "transcript_method": "mlx_whisper_large_v3_turbo", "transcript_status": "unverified",
        "topics": entry.get("topics", []), "raw_asr": str(asr_path.relative_to(WIKI)),
    }
    lines = ["---"]
    for key, value in metadata.items():
        if value is not None:
            lines.append(f"{key}: {json.dumps(value, ensure_ascii=False)}")
    lines += [
        "---", "", f"# {entry['title']}", "", f"[Watch the original video]({entry['url']})", "",
        "> [!warning] Automated transcript",
        "> This transcript was generated by speech-to-text and has not been human-reviewed. Verify wording against the video before relying on a quotation.",
        "", "## Transcript", "",
    ]
    for start, text in transcript_blocks(segments):
        seconds = int(start)
        lines += [f"[{timestamp(start)}]({entry['url']}&t={seconds}s) {text}", ""]
    YOUTUBE_SOURCES.mkdir(parents=True, exist_ok=True)
    path = YOUTUBE_SOURCES / f"{safe_filename(entry['title'])} [{entry['video_id']}].md"
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int)
    parser.add_argument("--shortest-first", action="store_true")
    args = parser.parse_args()
    try:
        import mlx_whisper
    except ImportError as error:
        raise SystemExit("mlx_whisper is unavailable; run with /usr/bin/python3 on this Mac") from error

    entries = [json.loads(line) for line in MANIFEST.read_text(encoding="utf-8").splitlines() if line.strip()]
    existing = note_map()
    queue = [entry for entry in entries if entry["video_id"] not in existing]
    if args.shortest_first:
        queue.sort(key=lambda entry: entry.get("duration_seconds") or 10**9)
    if args.limit is not None:
        queue = queue[:args.limit]
    state = {"model": MODEL, "total_queued": len(queue), "completed": 0, "failed": 0, "errors": []}
    write_state(state)
    started = time.time()
    for index, entry in enumerate(queue, 1):
        audio = None
        state["current"] = {"index": index, "source_id": entry["source_id"], "title": entry["title"]}
        write_state(state)
        try:
            print(f"[{index}/{len(queue)}] {entry['title']}", flush=True)
            audio = download_audio(entry)
            result = mlx_whisper.transcribe(str(audio), path_or_hf_repo=MODEL, language="en", verbose=False)
            segments = normalize_segments(result)
            if not segments:
                raise RuntimeError("speech-to-text returned no timestamped segments")
            asr = save_asr(entry, result, segments)
            path = write_note(entry, asr, segments)
            state["completed"] += 1
            print(f"  wrote {path.relative_to(ROOT)} ({len(segments)} segments)", flush=True)
        except KeyboardInterrupt:
            write_state(state)
            raise
        except Exception as error:
            state["failed"] += 1
            state["errors"].append({"source_id": entry["source_id"], "error": str(error)[:500]})
            print(f"  ERROR: {error}", flush=True)
        finally:
            if audio:
                audio.unlink(missing_ok=True)
            state.pop("current", None)
            write_state(state)
    state["status"] = "complete"
    state["elapsed_seconds"] = round(time.time() - started, 1)
    write_state(state)
    print(f"Done: {state['completed']} completed; {state['failed']} failed.")


if __name__ == "__main__":
    main()
